apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  # Default port of mongodb + karena backend hardcoded ke 27017
  ports:
  - port: 27017
    targetPort: 27017