apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # Sesuai permintaan. Harus di encode ke base64
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
  MONGO_ROOT_USERNAME: YWRtaW4=
