# Notes from Kaenova: Ini aku ambil dari template GO awalnya yang dari CircleCI
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  # Lint jobs
  lint-dockerfile:
    docker:
      - image: docker:20.10.23
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: docker pull ghcr.io/hadolint/hadolint < Dockerfile
  
  # Test jobs
  test-app:
    docker:
      - image: golang:1.15.15-alpine3.14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Run tests
          command: |
            go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: docker:20.10.23
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Login Docker Github
          command: echo $PASSWORD_DOCKER_HUB | docker login -u $USERNAME_DOCKER_HUB --password-stdin ghcr.io
      - run:
          name: Build Docker Image
          command: docker build -t ghcr.io/${DOCKER_REGISTRY}:latest -f Dockerfile .
      - run:
          name: Push Docker Image
          command: docker push -t ghcr.io/${DOCKER_REGISTRY}:latest


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  lint-test-build-karsajobs: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - lint-dockerfile
      - test-app:
          name: test-app
          requires:
            - lint-dockerfile
      - build-app-karsajobs:
          name: build-app-karsajobs
          requires:
            - test-app